---
 - name: Download petclinic war from nexus
   get_url:
     url: "http://{{ NEXUS_IP }}:{{ nexus_port }}/nexus/content/repositories/releases/org/springframework/samples/spring-petclinic/4.2.{{ BUILD_NO }}/spring-petclinic-4.2.{{ BUILD_NO }}.war"
     dest: "{{ TOMCAT_HOME }}/webapps/petclinic.war"
     url_username: "{{ NEXUS_USER }}"
     url_password: "{{ NEXUS_PASS }}"
     validate_certs: no
   notify: restart tomcat
